### ISSUE TITLE
Cyrillic subtitles bug

### ISSUE THREAD

**Issue by rado84bg** [linuxmint/xplayer#103]
```
 * Xplayer version (xplayer --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**
Cyrillic subs - one particular letter appears with horns.

**Steps to reproduce**
Choose Windows-1251 for subtitles (that's the encoding for Bulgarian subtitles).
Choose Noto Sans Bold, size 10 or higher - bug best viewed with size 10 with at least 1080p resolution.
Play any movie and wait for the character Bulgarian M to appear. Bug is best seen when the letters are on white or any other light background.
See the screenshot under "Other information".

**Expected behaviour**
Letters should not have horns.

**Other information**
![2018-05-11 16-54-04](https://user-images.githubusercontent.com/39193979/39928661-a169aa86-553e-11e8-9e95-363c39930c4b.png)
This bug appears ONLY in Xplayer! In all other players I've tried the subs have no horns.

**Comment by leigh123linux** [comment]
Next time use the template!

**Comment by rado84bg** [comment]
Next time go fuck yourself, retard!

**Comment by clefebvre** [comment]
Wow, that's a really weird bug.. 

is that letter U+041C?
does that happen with totem as well?

I'll have to check, but as far as I know the subs are rendered through gstreamer.

PS: Please be more respectful towards each others (both of you). I don't think I'm the only dev to think like that, it doesn't push people to come and participate, quite the opposite.
