### ISSUE TITLE
Question: how to make codec plugin from existing library?

### ISSUE THREAD

**Issue by Wohlstand** [linuxmint/xplayer#116]
Hello!

I have my own MIDI playing libraries which I using for various purposes: as standalone simple players, as in-game music playing (SDL Mixer X and GZDoom), as VLC plugins, as RT MIDI drivers and VST plugins are made by my friend, etc.

I am interested to make the codec plugin for XPlayer too.

My libraries are here: There are can work as file player with seek-ability and direct file parsing as well as Real-Time MIDI players to receive MIDI commands and interpret them immediately.
https://github.com/Wohlstand/libADLMIDI
https://github.com/Wohlstand/libOPNMIDI

**Comment by leigh123linux** [comment]
xplayer uses gstreamer1 codecs

https://gstreamer.freedesktop.org/
