### ISSUE TITLE
Green Screen

### ISSUE THREAD

**Issue by callagg2** [linuxmint/xplayer#142]
```
 * Xplayer version (xplayer 2.0.2)
 * Distribution - (Mint 19.1, Cinnamon...)
```

**Issue**
On playing "some" mp4/mkv files, the screen is green (the audio of the movie plays fine so it's not that the file does not play). The very same file plays without issue in VLC.

**Steps to reproduce**
Find a mp4 file (H264 MPEG-4 AVC (part 10) AVC1)
check in VLC codec information if the "video resolution" differs to the "buffer resolution"
If the two resolutions differ you get a green screen in xplayer, 
but if they are the same resolution you can see the file fine. 
I can confirm it happens to me with over 23 mp4 files.

**Expected behaviour**
The file should play the same as it does in VLC

**Other information**
I'm having no issues with the flv/avi/mpg/web files.

**Comment by muzena** [comment]
@callagg2 
Try to remove 'mesa-va-drivers' package.

**Comment by callagg2** [comment]
Muzena,
I tried "sudo apt purge mesa-va-drivers" then rebooted, but it has made no change - it is still green.

This is my current set-up
inxi -G
Graphics:
  Device-1: Intel Core Processor Integrated Graphics driver: i915 v: kernel 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1366x768~60Hz, 1280x720~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ironlake Mobile v: 2.1 Mesa 18.0.

**Comment by callagg2** [comment]
Muzena,
I just tried the exact same mp4 file on another laptop.
Linux Mint 19.1 but this time with XFCE, same version of xplayer.
It plays fine.

Graphics:
Device-1: Nvidia C79 [GeForce 9400M] Driver: nouveau v:kernel
Display: x11 server: X.Org 1.19.6 driver: nouveau 
unloaded: fbdev,modesetting,vesa resolution: 1280x800-61Hz
OpenGL: renderer: NVAC v3.3 Mesa 18.0.5

okay, well that's good, it is obviously specific to this Dell laptop

**Comment by callagg2** [comment]
Muzena,
I've tried a Dell desktop on Cinnamon 4 and its fine.
So 2 out of 3 devices are fine, so close this bug, its obviously something stupid with my Dell laptop.
Apologies for wasting your time

**Comment by muzena** [comment]
@clefebvre
sudo apt remove gstreamer1.0-vaapi
Command removes mint-meta-codecs package in Mint 19.01

**Comment by muzena** [comment]
Solution for this is to add config lines in /etc/drirc file like in this [comment](https://bugs.launchpad.net/ubuntu/+source/gstreamer-vaapi/+bug/1767312/comments/16)

**Comment by callagg2** [comment]
Muzena, 
I'm now using a different laptop and this issue is still here in Kernel: 4.15.0-55-generic x86_64 bits: 64 
Desktop: Cinnamon 4.2.2 Distro: Linux Mint 19.2 Tina 
Type: Laptop System: Dell product: Latitude E4310 v: 0001  serial: <root required>   Mobo: Dell model: 0XG3JF v: A00 serial: <root required> BIOS: Dell v: A15  date: 05/12/2017 
Graphics:
  Device-1: Intel Core Processor Integrated Graphics driver: i915 v: kernel 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1360x768~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ironlake Mobile v: 2.1 Mesa 19.0.2 
Xplayer 2.2.1

That comment you referred me to, i have no such folder on my system  /etc/drirc.

So, I have now tested over 30 videos files (MP4, FLV and MKV).
I tested about 10 videos where the  Video resolution = the Buffer resolution
and 11 videos where  Video resolution differs to the Buffer resolution.
For example, these were the resolutions that gave the problems: 
Video resolution 320 x 210
Buffer dimension 320 x 224

Video resolution 480 x 270
Buffer dimension 480 x 272

Video resolution 480 x 360
Buffer dimension 480 x 368

Video resolution 640 x 264
Buffer dimension 640 x 272

Video resolution 640 x 360
Buffer dimension 640 x 368

Video resolution 664 x 272
Buffer dimension 672 x 272

Video resolution 1012 x 506
Buffer dimension 1024 x 512

Video resolution 1056 x 442
Buffer dimension 1056 x 448

Video resolution 1280 x 536
Buffer dimension 1280 x 544

Video resolution 1800 x 1080
Buffer dimension 1808 x 1088

Video resolution 1920 x 804
Buffer dimension 1920 x 816

I can confirm that if the Video resolution differs to the Buffer resolution 
- I get a green screen in both Xplayer and Totem,
 but VLC, MPV media player and Gnome MPV are fine.

Anytime the resolutions are the same, no green screen in Xplayer and Totem.

**Comment by leigh123linux** [comment]
Report the issue against gstreamer1.0-vaapi

**Comment by leigh123linux** [comment]
Can someone affected by this install vainfo and run
```
vainfo
```

Then post the output here

**Comment by callagg2** [comment]
Is this any help?

~$ vainfo
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Ironlake Mobile - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc

and if needed
$ inxi -G
Graphics:
  Device-1: Intel Core Processor Integrated Graphics driver: i915 v: kernel 
  Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1360x768~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel Ironlake Mobile v: 2.1 Mesa 19.0.2 

System:    Host: Latitude-E4310 Kernel: 4.15.0-55-generic x86_64 bits: 64 Desktop: Cinnamon 4.2.3 
 Distro: Linux Mint 19.2 Tina 
  Machine:   Type: Laptop System: Dell product: Latitude E4310 v: 0001 serial: <root required> 
  Mobo: Dell model: 0XG3JF v: A00 serial: <root required> BIOS: Dell v: A15 date: 05/12/2017
