### ISSUE TITLE
Red-ish Picture

### ISSUE THREAD

**Issue by w4r0** [linuxmint/xplayer#146]
```
 * Xplayer version 2.02
 * Distribution - (Mint 19.1)
```

**Issue**
Every video files I play rendered as red or pink colors.

**Steps to reproduce**
Open file and play.

**Expected behaviour**
Picture with normal color.

**Other information**
![image](https://user-images.githubusercontent.com/2328329/55684796-8f346000-5979-11e9-8f67-4d565ddb8baf.png)

**Comment by J0Ar** [comment]
Same problem. Solved after removing the **gstreamer1.0-vaapi** package.

> System:    Host: Mint191 Kernel: 4.18.0-17-generic x86_64 bits: 64 compiler: gcc v: 7.3.0 
> Desktop: Cinnamon 4.0.10  wm: muffin 4.0.7 dm: LightDM 1.26.0 Distro: Linux Mint 19.1 Tessa
> base: Ubuntu 18.04 bionic 
> Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] vendor: XFX Pine driver: amdgpu v: kernel bus ID: 01:00.0 chip ID: 1002:67df 
> Display: x11 server: X.Org 1.19.6 driver: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa 
> resolution: 1600x900~60Hz  
> OpenGL: renderer: AMD Radeon RX 480 Graphics (POLARIS10 DRM 3.26.0 4.18.0-17-generic LLVM 7.0.0) v: 4.5 Mesa 18.2.8 compat-v: 4.4 direct render: Yes

**Comment by w4r0** [comment]
> Same problem. Solved after removing the **gstreamer1.0-vaapi** package.
> 
> > System:    Host: Mint191 Kernel: 4.18.0-17-generic x86_64 bits: 64 compiler: gcc v: 7.3.0
> > Desktop: Cinnamon 4.0.10  wm: muffin 4.0.7 dm: LightDM 1.26.0 Distro: Linux Mint 19.1 Tessa
> > base: Ubuntu 18.04 bionic
> > Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] vendor: XFX Pine driver: amdgpu v: kernel bus ID: 01:00.0 chip ID: 1002:67df
> > Display: x11 server: X.Org 1.19.6 driver: amdgpu,ati unloaded: fbdev,modesetting,radeon,vesa
> > resolution: 1600x900~60Hz
> > OpenGL: renderer: AMD Radeon RX 480 Graphics (POLARIS10 DRM 3.26.0 4.18.0-17-generic LLVM 7.0.0) v: 4.5 Mesa 18.2.8 compat-v: 4.4 direct render: Yes

I confirm this. After I remove gstreamer1.0-vaapi the problem is stopped. But when I remove it, apt also remove **mint-meta-codecs**, so if you use mint-meta-codecs, you have to reinstall it.

**Comment by leigh123linux** [comment]
The issue is in the ubuntu  gstreamer1.0-vaapi package, there's nothing to fix in xplayer.
