### ISSUE TITLE
xplayer does not play any kind of video

### ISSUE THREAD

**Issue by RafaMartorell** [linuxmint/xplayer#152]
```
 * Xplayer version xplayer -- 1.6.1
 * Distribution - Mint 18.3
```

**Issue**
xplayer does not play any kind of video, the following error comes out
"An error has occurred, the support library could not be initialized"

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
If xplayer can't play video you will need to install the missing gstreamer1-plugins-* packages that provide the required video codecs.
Also if you want your report to be taken seriously you need to provide a lot better info like:

1: what file type?

mediainfo whatever_file

2: output for xplayer command.

3: maybe a screenshot of the error dialog.

**Comment by RafaMartorell** [comment]
1: what file type? mp4
"An error has occurred, the support library could not be initialized"

**Comment by leigh123linux** [comment]
mp4 isn't what I wanted and doesn't describe the codec type!

**Comment by clefebvre** [comment]
This usually happens because of vaapi.

Can you see if gstreamer1.0-vaapi is installed, and if so, remove it.

**Comment by clefebvre** [comment]
Long story short xplayer uses clutter-gst which doesn't play well with acceleration. We should consider getting rid of it, either by using gstreamer directly or basing the backend on something like mpv.

**Comment by RafaMartorell** [comment]
It must be a problem to have installed many multimedia applications, but it does not matter I deleted xplayer and now I use vlc which is great.
Thank you very much for the help.
