### ISSUE TITLE
Thumbnails for 10bit H264/AVC videos are displayed with wrong colors

### ISSUE THREAD

**Issue by Meru** [linuxmint/xplayer#156]
```
 * Nemo  4.0.6
 * Is issue with: Windowed
 * Distribution: Mint 19.1
 * Graphics hardware: not relevant
 * 64bit
 ```

**Issue**
Previews for 10bit H264/AVC videos are displayed with wrong colors:
https://i.imgur.com/TtBlNwC.png

**Steps to reproduce**
Just browse to the file in question, switch to Icon View to see better.

**Expected behaviour**
Colors should be correct (not everything green-n-purple!)

**Other information**
This may be not a problem with nemo per se, but not sure where else I can put this.

It looks like 2 extra bits got clamped at some point during conversion. Interestingly, this does not happen with 10bit h265/HEVC files.
switching to ffmpegthumbnailer as generator produces correct results (but also draws an ugly frame around previews, win7-style).
Default xplayer for example shows correct colors during playback.

Edit: sample files https://www.koi-sama.net/files/hi10/

**Comment by leigh123linux** [comment]
@Meru without more info I would blame gstreamer1 codec
