### ISSUE TITLE
syntax error near unexpected token `WARN_CFLAGS,WARN_LDFLAGS'

### ISSUE THREAD

**Issue by bertvandepoel** [linuxmint/xplayer#174]
```
 * Xplayer version: git master 
 * Distribution: Ubuntu 24.04
```

**Issue**

Unable to compile. After taking a long while to resolve issues with dependencies (including xplayer-plparser), I now no longer run into dependency issues but a syntax error.

When using ./autogen.sh I get:
```
checking pkg-config is at least version 0.16... yes
./configure: line 23875: syntax error near unexpected token `WARN_CFLAGS,WARN_LDFLAGS'
./configure: line 23875: `AX_COMPILER_FLAGS(WARN_CFLAGS,WARN_LDFLAGS)'
```
If I do libtoolize --force; aclocal; autoheader; automake --force-missing --add-missing; autoconf; ./configure instead I get:
```
checking for gtk+-3.0 >= 3.5.2 xapp >= 1.0.0... yes
./configure: line 22366: syntax error near unexpected token `newline'
./configure: line 22366: `LIBGD_INIT('
```

**Steps to reproduce**

Attempt to run ./autogen.sh with all dependencies installed

**Expected behaviour**

./configure to pass so I can make and then make install

**Other information**

As mentioned in #173 I would expect this to compile and work due to recent commitments by the Linux Mint project to develop and maintain more independent applications through x-apps, and this is something I want to support (I also just really like xplayer).

**Comment by leigh123linux** [comment]
You haven't installed the required deps, you missed.

https://github.com/linuxmint/xplayer/blob/master/debian/control#L10

Install all the deps listed in that file and then try compiling the latest git snapshot.

**Comment by bertvandepoel** [comment]
I see. So there are dependencies not being checks by the ./configure file nor listed in the INSTALL or README. Should I submit a PR to perhaps point people to that file you linked? @leigh123linux

**Comment by leigh123linux** [comment]
TBH I don't understand why your not using the debian packaging in 

https://github.com/linuxmint/xplayer/blob/master/debian/

See https://www.debian.org/doc/manuals/maint-guide/build.en.html#autobuilder

**Comment by bertvandepoel** [comment]
I don't know how to debian package things. I'm just a user of xplayer and far from an expert. I just looked at the README and INSTALL and then followed the instructions. So both xplayer and xplayer-plparser I can compile-package myself using that stuff? I had no idea, but I'll try it in a bit since after installing what you said, I now get compiler errors due to strictness.

**Comment by leigh123linux** [comment]
You would avoid these issues using the debian packaging.
compiler errors are expected due to the default -Werror, you need to disable it, see


https://github.com/linuxmint/xplayer/blob/master/debian/rules#L16

**Comment by bertvandepoel** [comment]
Thanks for letting me know I could follow the Debian packaging side of things. I've now got it working with a ppa, so that's quite convenient https://launchpad.net/~bhack/+archive/ubuntu/xplayer . Thanks a ton!
