### ISSUE TITLE
Subtitle downloader

### ISSUE THREAD

**Issue by muzena** [linuxmint/xplayer#18]
Subtitle downloader don't work.

**Comment by clefebvre** [comment]
fixed by https://github.com/linuxmint/xplayer/commit/0d33e80852681572a52c6cb124a0541f0d881abe

**Comment by muzena** [comment]
@clefebvre 
I have installed this package before when I tried playback, and today but subtitle downloader don't work, I tried totem player 3.18 and subtitler downloader work, I think you shuould update subtitle downloader plugin source code from totem 3.18 or 3.20 there been some changes in code and maybe opensubtitles APi.
