### ISSUE TITLE
xplayer doesn't allow to select a new default video player for avi and 3gp

### ISSUE THREAD

**Issue by KDB2** [linuxmint/xplayer#19]
Dear team,

Please note that xplayer doesn't allow to select a different default video player for the following format:
avi and 3gp.

When you press the select as default button, it reverts immediately to xplayer. 

KDB

Edit: LMDE2 + Cinnamon 3.0

**Comment by clefebvre** [comment]
Hi KDB,

This looks like a Cinnamon issue.
