### ISSUE TITLE
Please Add Hotkey to Toggle Subtitle On/Off

### ISSUE THREAD

**Issue by ttjimera** [linuxmint/xplayer#28]
Right now, we can only toggle subtitle on/off via menu. This is inconvenient when watching video in full-screen mode. There are certain movies where the characters speak various languages and we only need the subtitle when they are speaking languages we do not know. But we do not want to pause the video and turn subtitle on/off each time they speak another language. So having this feature would be really convenient.

**Comment by clefebvre** [comment]
Coming up in version 1.4.x.

Use L for language and S for subtitles.

**Comment by ttjimera** [comment]
Thank you very much. Looking forward to it.
