### ISSUE TITLE
Hardware Acceleration

### ISSUE THREAD

**Issue by ryu0** [linuxmint/xplayer#31]
On Linux Mint 18, even with the gstreamer libva module and the libva drivers installed, it does not appear that H264 is being decoded through hardware. The CPU usage goes up to 50% while VLC, which is using vpdau, is less than 20% on the same video stream. What's the deal here?

**Comment by leigh123linux** [comment]
You need gstreamer1.0-vaapi installed for hardware acceleration, this method will never equal vpdau performance with nvidia hardware.

**Comment by leigh123linux** [comment]
Closed, you will need to file the issue against gstreamer*
