### ISSUE TITLE
Integration of Xplayer into Sound Applet

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/xplayer#34]
Note the following is also true for totem (in LM 17.x). Just replace the expression xplayer with totem in the following description.

It appears not logical that xplayer is the default multimedia player in Mint Cinnamon, but is not (as least not by default) supported by the sound applet.

To get the support only 2 easy preconditions have to be met:
1. There must get an entry into ~/.cinnamon/configs/sound@cinnamon.org/sound@cinnamon.org.json, near the end of the file, so that it reads (partial excerpt):
     "_knownPlayers": {
        "type": "generic",
        "default": [
            "banshee",
            "vlc"
        ],
        "value": [
            "banshee",
            "vlc",
            "xplayer"
        ]
    },
The line which says "xplayer" does not exist by default, but must be added. Note, that in case of totem it must actually read "totem" and not "xplayer" on this place.
Result: The program appears in the menu list of the applet and can be launched by this.
1. The D-Bus plugin in xplayer must be activated. At now it is deactivated by default, so that every user has to do this on its own. As said, as this is the default player the plugin should be activated by default.
   Result: The program can get controlled by the applet.

If the plugin gets activated, it automatically inserts the above line in the config file for the applet, so that the user does actually not have to do this manually. This automatism might probably not longer work, if the plugin should get activated by default.

Additional note: The needed package xplayer-plugins do not get installed by upgrading with the mintupgrade tool, only on a fresh install. (In contrast to xplayer-plugins-extra, which get installed on both ways.)

**Comment by clefebvre** [comment]
xplayer was added to the list of players without seek support.
dbus plugin is now enabled by default.
dbus plugin now shows media name for files without metadata.
