### ISSUE TITLE
Xplayer cant load supported library's

### ISSUE THREAD

**Issue by bitking** [linuxmint/xplayer#35]
Hi there,

When loading a avi/divx file i get the following message.

"Cant load supported library's" and the file isnt played.

Setup: 
Linux Mint 18
Xplayer 1.0.7
Videofiles: MPEG 4 XVID
## This is what i see in the syslog:

Sep  4 08:59:18 johan-N76VM org.mate.panel.applet.MintMenuAppletFactory[3785]: [2016-09-04 08:59:18,833 pyinotify ERROR] rm_watch: cannot remove WD=125, Errno=Ongeldig argument (EINVAL)
Sep  4 08:59:21 johan-N76VM org.mate.panel.applet.MintMenuAppletFactory[3785]: *\* (mate-control-center:3919): WARNING **:
Sep  4 08:59:21 johan-N76VM org.mate.panel.applet.MintMenuAppletFactory[3785]: error raised: [load_xbel_store: couldn't load bookmark file [NULL]
Sep  4 08:59:21 johan-N76VM org.mate.panel.applet.MintMenuAppletFactory[3785]: ]

This is what i see in the debug log:
(xplayer:6188): Gtk-WARNING **: Could not find signal handler 'popup_remove_action_cb'.  Did you compile with -rdynamic?
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)

**Comment by clefebvre** [comment]
Remove gstreamer1.0-vaapi.
