### ISSUE TITLE
The control bar is too large

### ISSUE THREAD

**Issue by lqmanh** [linuxmint/xplayer#36]
Maybe it is just me, but I find the control bar is too spacious. I believe it would be more beautiful if you reduce the size of it.
Thanks

**Comment by JosephMcc** [comment]
Do you have links or screenshots to something you feel uses a better layout?

**Comment by Lq-Manh** [comment]
![screenshot from 2016-09-26 19-02-47](https://cloud.githubusercontent.com/assets/20436482/18833632/db189cc4-841b-11e6-92d7-70e055d72ef3.png)
As you can see, VLC player's control bar is much more compact. Xplayer's control bar and menu bar seem too take up one-third of my screen.
In fact, not only Xplayer but also all Xapps do I find somewhat unnecessarily spacious.

**Comment by JosephMcc** [comment]
A lot of the space you are talking about in other xapps is being eaten up by the icon style toolbar. In xed, for example, you can hide the toolbar completely.

**Comment by Vahan86** [comment]
Agree with Lq-Manh, would be nice to have more modern design for Xplayer.

**Comment by focusime** [comment]
For me, the most ideal interface is a floating control bar over the movie which appears only when you move the mouse (somewhat like the youtube ). So that there is no unnecessary space when watching but still easy to contrl the progress or volumn when needed.

**Comment by JosephMcc** [comment]
Changes were just merged to redesign the playbar:
![media player_021](https://cloud.githubusercontent.com/assets/2231759/23001019/0003e124-f398-11e6-8ed6-63babbe76053.png)
