### ISSUE TITLE
Selection of audio and subtitles language

### ISSUE THREAD

**Issue by muzena** [linuxmint/xplayer#37]
Can some of developers add options in Xplayer preferences for selecting audio and subtitles language.
When I start eg. mkv movie it has a few audio tracks, and 10-15-20 subtitles track, and every time i must manually select from menu audio and subtitle track.
It seems to select first of audio and first subtitle track, and it's always director comments, and arabic subtitles.

**Comment by clefebvre** [comment]
Hi,

This was implement recently (available in upcoming 1.4.x). Use L to switch language and S for subtitles.
