### ISSUE TITLE
XPlayer doesn't honor the user's theme

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/xplayer#38]
I'm using Vertex Light theme but XPlayer uses the dark flavor. There should at least be a setting, which theme to use.

This is an misfeature Totem suffers from since GNOME 3.2.

**Comment by JosephMcc** [comment]
I would be ok with a setting but would not want this feature removed. It's also partly up to your theme. In Mint-Y we don't include a dark theme for just this reason but we do include one in Mint-Y-Darker.

**Comment by marmistrz** [comment]
I'm all for a setting.
