### ISSUE TITLE
The OSD icons (play, pause, skip) is too big and intrusive.

### ISSUE THREAD

**Issue by JoDo77** [linuxmint/xplayer#53]
Hi! The OSD icons (play, pause, skip) is too big and intrusive. Usually displayed in fullscreen mode. It's distracting. I enclose a screenshot of Xplayer and to compare also screenshot of VLC. Thank you for considering the situation.
![osd-xplayer](https://cloud.githubusercontent.com/assets/23626543/20472854/0926cd1c-afbd-11e6-8fbe-df4df99edcbe.png)
![osd-vlc](https://cloud.githubusercontent.com/assets/23626543/20472856/0df4913a-afbd-11e6-8dea-e78cd3fb9e48.png)

**Comment by clefebvre** [comment]
Oh yes, I see it... and they also don't appear all the time. They look completely broken in fact :)

**Comment by cossio** [comment]
This happens to me as well... but I can't pin point a procedure to reproduce the issue all the time. Seems sporadic.

**Comment by cossio** [comment]
By the way, this happened in totem too, so it must be in the common code base.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/xplayer/commit/38aeea83cc2101e780554f8bff0bb558895da604

**Comment by cossio** [comment]
@clefebvre Thanks! Better to remove the icons. They don't do any good.
