### ISSUE TITLE
Commenting the source code

### ISSUE THREAD

**Issue by Schallaven** [linuxmint/xplayer#62]
I just started digging through the code and maybe I am the only one, but I think the code needs more comments and documentation. 

C code is already hard to maintain. C code implementing pseudo OO is even harder. And C code, which is only marginally commented is even worse. IMHO it prevents people from contributing to this project.

I wanted to just open this issue for reference - I want to go through the files step by step and see what I can do for documentation. Hope this is ok!

**Comment by JosephMcc** [comment]
Code that is overly laced with comments is annoying. If it's sensibly designed and uses decent naming for functions, variables, etc. a ton of comments aren't needed. Comments should mostly be reserved for things that are non-obvious or possibly where things are done in an unexpected way to give a clue as to why they were done that way. The source code isn't meant to be a tutorial on writing C.
