### ISSUE TITLE
gstreamer Dolby TrueHD decoder plugin missing

### ISSUE THREAD

**Issue by muzena** [linuxmint/xplayer#64]
@clefebvre 
I get this error in terminal when I trying to play mkv's with multiple audio track, only first track is available.

** Message: Missing plugin: gstreamer|1.0|xplayer|Dolby TrueHD decoder|decoder-audio/x-true-hd (Dolby TrueHD decoder)
/usr/lib/python3/dist-packages/sessioninstaller/core.py:47: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gst
/usr/lib/python3/dist-packages/sessioninstaller/core.py:48: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk

**Comment by clefebvre** [comment]
Hi,

> /usr/lib/python3/dist-packages/sessioninstaller/core.py:47: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
> from gi.repository import Gst
> /usr/lib/python3/dist-packages/sessioninstaller/core.py:48: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
> from gi.repository import Gtk
> 

These are only warnings.

> ** Message: Missing plugin: gstreamer|1.0|xplayer|Dolby TrueHD decoder|decoder-audio/x-true-hd (Dolby TrueHD decoder)

That explains why you have an issue.

I went ahead and tested the following codecs:

- Dolby TueHD 5.1
- Dolby TrueHD 7.1
- Dolby TrueHD 7.1 ATMOS

All of them with sample videos downloaded from http://thedigitaltheater.com/index.php/dolby-trailers/.

They're all working fine here.

**Comment by clefebvre** [comment]
In Mint make sure mint-meta-codecs is installed, these codecs are associated with ffmpeg and libav.

**Comment by muzena** [comment]
@clefebvre 
I have installed mint-meta-codecs package and i try to reinstall this package but does not work.
