### ISSUE TITLE
unable to launch mozilla-viewer in Manjaro (xplayer 1.4.1)

### ISSUE THREAD

**Issue by oberon2007** [linuxmint/xplayer#71]
I have built **xplayer 1.4.1** with ``--enable-browser-plugins=yes``, yet mozilla-viewer appears to be unable to launch:

![](http://imgur.com/QixtvXg.png)

I have just checked and **/usr/share/xplayer/mozilla-viewer.ui** seems to be installed correctly.
What can be wrong here?

**Comment by oberon2007** [comment]
Is this possibly a gtk issue? On Manjaro we are currently running **gtk3 3.22.15**

**Comment by oberon2007** [comment]
bump. Any pointers for us, maybe?

**Comment by leigh123linux** [comment]
Closed https://github.com/linuxmint/xplayer/commit/71c06f8a82b284d6b5c08096a1465eebb71b39b8
