### ISSUE TITLE
Status bar play file size

### ISSUE THREAD

**Issue by mywayfr** [linuxmint/xplayer#73]
Hello,
On mint cinnamon 18.2 beta with xplayer.
Coming to full screen the name of the current playing file is show in the bottom status bar.
But it take almost all the size of it!
It become difficult to use the movie line (in windowed mode it take all the place more easier)
So if it's possible to restrain the number of letter aviable for the current playing file I think it will be a good things.
Many thanks for your great work

**Comment by JosephMcc** [comment]
It does seem to take a bit more room than it really needs to.

**Comment by mywayfr** [comment]
Thanks you for tacking my asking to a "feature request".
Cheers
