### ISSUE TITLE
Hercules Disney DVD crashes Xplayer and sometimes causes kernel panic

### ISSUE THREAD

**Issue by toothpasteman** [linuxmint/xplayer#81]
```
 * Xplayer version (xplayer 1.4.3)
 * Distribution - (18.3)
```

Sorry, I'm new to GitHub bug reports, let me know if I did anything wrong

**Issue**
So I went to Amazon and bought the Hercules Disney DVD for my daughter (since internet is to slow to stream stuff here), went to play it and xplayer immediately crashed, weird I thought, so I tried multiple times, and same thing. I tried with VLC and it worked perfectly. OK, tried with 40 other different movies and works perfectly, so this must be a hardware thing right? No! I tried on a laptop with Mint 18.3 and same thing, crashes xplayer and works with VLC, except on the laptop it sometimes causes a kernel panic. So I tried on a Ubuntu 17.04 desktop and compiled xplayer from source, and same thing! I tried with Totem, and it works perfectly. I tried doing a stack trace and it shows nothing, and the terminal output shows nothing even with the dbg package installed. Ok I thought, there must be something fucked with this DVD, so I went on amazon and bought 3 more to test and SAME EXACT THING. I am lost at this point and I am even willing to ship out the DVD in question for the developers to test.

 
**Steps to reproduce**
Play the god damn Hercules Disney DVD and watch your computer get fucked in the ass by Hades himself

![image](https://user-images.githubusercontent.com/31904083/30349838-ab38af4c-97d1-11e7-9a69-af23a2bcf737.png)

**Expected behaviour**
For the DVD to work

**Other information**
None

**Comment by clefebvre** [comment]
I've seen xplayer segfault with vaapi or vdpau... clutter-gst doesn't like it too much. Other than that... I need a backtrace.

We're working on a new tool called mintreport, which simplifies getting backtraces, give it a try in case it helps. It's on github as well.

**Comment by clefebvre** [comment]
I'll close that as it's not something we can work on just yet. Don't hesitate to reopen it or to create a new issue if you get more info about the crash.
