### ISSUE TITLE
10-bit video have washed out colors

### ISSUE THREAD

**Issue by RP-11** [linuxmint/xplayer#90]
```
 * Xplayer version (xplayer --version) 1.6.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
```

**Issue**
10-bit videos (HEVC) have washed out colors compared to MPV (the only player on mint that is capable of reproducing 10-bit colors)

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
This need to be reported against gstreamer1*
