### ISSUE TITLE
Play back of avi encoded with H265 does not work

### ISSUE THREAD

**Issue by Reiner1210** [linuxmint/xplayer#96]
```
xplayer 1.6.1
Mint 18.3

**Issue**
Play back of avi encoded with H265 does not work
Codec not found


**Steps to reproduce**
Example file:
http://tmp.natureimpression.com/test.avi

**Expected behaviour**
Video should be shown :-)


**Other information**

**Comment by leigh123linux** [comment]
gstreamer1-plugins-* packages provide the codecs, if it doesn't handle the format it's their issue.
Totem can't play it either and I have all gst-plugins installed

```
totem test.avi 
** Message: 11:51:40.707: Missing plugin: gstreamer|1.0|totem|video/x-avi-unknown decoder|decoder-video/x-avi-unknown, fourcc=(int)829842792 (video/x-avi-unknown decoder)
```

**Comment by Reiner1210** [comment]
Mplayer can play it

Mit AquaMail Android
http://www.aqua-mail.com gesendet


Am 17. Februar 2018 13:24:19 schrieb Leigh Scott <notifications@github.com>:

**Comment by Reiner1210** [comment]
It is not really a codec problem. The problem is to recognize the FourCC 
tag in the avi for it

Mit AquaMail Android
http://www.aqua-mail.com gesendet


Am 17. Februar 2018 13:24:19 schrieb Leigh Scott <notifications@github.com>:

**Comment by leigh123linux** [comment]
Mplayer doesn't use gstreamer codecs.

**Comment by leigh123linux** [comment]
Does this help?

https://ubuntuforums.org/showthread.php?t=2379481
