### ISSUE TITLE
Make SPACE pause/play video

### ISSUE THREAD

**Issue by marko-avlijas** [linuxmint/xplayer#98]
Why is this set to CTRL+space?
What a bizarre decision.

Please make it standard like VLC Player, youtube and basically every other program does it.

**Comment by The-Phi** [comment]
On which distro are you? No problem on Xfce.

**Comment by marko-avlijas** [comment]
I am on linux mint 18.2 / cinnamon

**Comment by dotnetCarpenter** [comment]
@The-Phi linux mint 19 / xfce
