### ISSUE TITLE
Some of the video thumbnails are not generated

### ISSUE THREAD

**Issue by DanyGee** [linuxmint/xplayer#99]
```
 * Xplayer version (xplayer 1.6.1)


 * Distribution - (Mint18.3)
```

**Issue**
Some of the video thumbnails are **not being generated** on my actual system.
But thumbnails for **the very same files are being generated** when tested on a fresh Mint18.3 install in a Virtual Machine (Virtualbox).
I would like to know where to start some troubleshooting :face_with_head_bandage: 

**Steps to reproduce**
Open the video folder. Check if all thumbnails are generated.

**Expected behaviour**
All video thumbnails should be created.

**Other information**

Properties of the files without thumbs:
Container: ISO MP4/M4A
Res: 1920 x 1080
Codec: H.264 (Main Profile)
Framerate: 25 fps
Bitrate: 9814 kb/s

Container: ISO MP4/M4A
Res: 1920 x 1080
Codec: H.264 (High Profile)
Framerate: 24 fps
Bitrate: 2159 kb/s

I repeat, the same files have thumbs on fresh install!

System:    Host: linuxmint Kernel: 4.15.0-13-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.6.7 (Gtk 3.18.9) Distro: Linux Mint 18.3 Sylvia
Machine:   Mobo: ASUSTeK model: Z170-DELUXE v: Rev 1.xx Bios: American Megatrends v: 3504 date: 06/29/2017
CPU:       Quad core Intel Core i7-6700K (-HT-MCP-) cache: 8192 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 32064
           clock speeds: max: 4300 MHz 1: 4041 MHz 2: 4049 MHz 3: 4043 MHz 4: 3155 MHz 5: 3666 MHz 6: 3743 MHz
           7: 3642 MHz 8: 3934 MHz
Graphics:  Card: NVIDIA Device 1b80 bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 3840x2160@60.00hz
           GLX Renderer: GeForce GTX 1080/PCIe/SSE2 GLX Version: 4.6.0 NVIDIA 396.18 Direct Rendering: Yes
Audio:     Card-1 NVIDIA Device 10f0 driver: snd_hda_intel bus-ID: 01:00.1 Sound: ALSA v: k4.15.0-13-generic
           Card-2 Intel Sunrise Point-H HD Audio driver: snd_hda_intel bus-ID: 00:1f.3
Network:   Card-1: Intel Ethernet Connection (2) I219-V driver: e1000e v: 3.2.6-k bus-ID: 00:1f.6
           IF: enp0s31f6 state: up speed: 100 Mbps duplex: full mac: <filter>
           Card-2: Broadcom BCM4360 802.11ac Wireless Network Adapter bus-ID: 07:00.0
           IF: N/A state: N/A mac: N/A
           Card-3: Intel I211 Gigabit Network Connection driver: igb v: 5.4.0-k port: c000 bus-ID: 0b:00.0
           IF: enp11s0 state: down mac: <filter>
Drives:    HDD Total Size: 2570.6GB (4.0% used) ID-1: /dev/sda model: Samsung_SSD_850 size: 256.1GB
           ID-2: /dev/sdb model: Samsung_SSD_850 size: 1024.2GB
           ID-3: /dev/sdd model: KINGSTON_SH100S3 size: 120.0GB
           ID-4: /dev/sdc model: Crucial_CT1050MX size: 1050.2GB
           ID-5: /dev/sde model: KINGSTON_SV300S3 size: 120.0GB
Partition: ID-1: / size: 110G used: 97G (93%) fs: ext4 dev: /dev/sde1
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 29.0C mobo: N/A gpu: 0.0:52C
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 256 Uptime: 2:02 Memory: 2906.0/32101.8MB Init: systemd runlevel: 5 Gcc sys: 5.4.0
           Client: Shell (bash 4.3.481) inxi: 2.2.35

**Comment by leigh123linux** [comment]
You need to install whatever gstreamer1 plugin is needed for mp4 (maybe gst1-libav).

**Comment by DanyGee** [comment]
Installed this:
sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools
But it didn't help.

**Comment by leigh123linux** [comment]
Maybe you have this issue https://github.com/linuxmint/xplayer/issues/83

**Comment by DanyGee** [comment]
No, I didn't re-encode any of those videos.
The question is: Why they work on a fresh install?
